### ISSUE TITLE
Error caused by babel-eslint package

### ISSUE THREAD

**Issue by ro31337** [59naga/climb-lookup#1]
```
➜  climb-lookup git:(master) npm test

> climb-lookup@ test /Users/Roman/work/climb-lookup
> abigail cover,lint

+  83 ms @ @ Use ./package.json
+   5 ms @ @ Begin cover, lint ...
+   3 ms @ @ Run cover

> climb-lookup@ ava /Users/Roman/work/climb-lookup
> ava --require babel-register


  2 passed

+   3  s @ @ Done cover. Exit code 0.
+   1 ms @ @ Run lint
Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at monkeypatch (/Users/Roman/work/climb-lookup/node_modules/babel-eslint/index.js:59:32)
    at Object.exports.parse (/Users/Roman/work/climb-lookup/node_modules/babel-eslint/index.js:385:5)
    at parse (/Users/Roman/work/climb-lookup/node_modules/eslint/lib/eslint.js:596:27)
    at EventEmitter.module.exports.api.verify (/Users/Roman/work/climb-lookup/node_modules/eslint/lib/eslint.js:735:19)
    at processText (/Users/Roman/work/climb-lookup/node_modules/eslint/lib/cli-engine.js:186:27)
    at processFile (/Users/Roman/work/climb-lookup/node_modules/eslint/lib/cli-engine.js:226:18)
    at executeOnFile (/Users/Roman/work/climb-lookup/node_modules/eslint/lib/cli-engine.js:583:23)
+ 793 ms @ @ Done lint. Exit code 1.
+   2 ms @ @ End cover, lint. Exit code 0, 1.
npm ERR! Test failed.  See above for more details.
```

**Comment by 59naga** [comment]
thanks! :+1:
